name: agic

services:
  agic:
    container_name: agic
    build:
      context: ..
      dockerfile: Dockerfile
    image: agic
    env_file:
      - ../.dev.env
    environment:
      PG__HOST: agic-pg
      PG__PORT: "5432"
      REDIS__HOST: agic-redis
      REDIS__PORT: "6379"
      S3__ENDPOINT_URL: http://agic-minio:9000
    ports:
      - "${APP_PORT}:8003"
    command: "./.venv/bin/uvicorn bootstrap.main:create_app --host 0.0.0.0 --port 8003 --factory"
    networks:
      - backend

networks:
  backend:
    driver: bridge
