name: project-name

services:
  project-name-minio:
    image: quay.io/minio/minio:latest
    container_name: project-name-minio
    env_file:
      - ../.dev.env
    command: server /data --console-address ":${MINIO__CONSOLE_PORT}"
    environment:
      MINIO_ROOT_USER: ${MINIO__ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO__ROOT_PASSWORD}
    ports:
      - "${MINIO__API_PORT}:9000"
      - "${MINIO__CONSOLE_PORT}:9001"
    volumes:
      - project_name_minio_data:/data
    networks:
      - backend

volumes:
  project_name_minio_data:
    name: docker_compose_project_name_minio

networks:
  backend:
    driver: bridge
