name: agic

services:
  agic-pg:
    image: pgvector/pgvector:pg17
    container_name: agic-pg
    env_file:
      - ../.dev.env
    environment:
      POSTGRES_DB: ${PG__DB}
      POSTGRES_USER: ${PG__USER}
      POSTGRES_PASSWORD: ${PG__PASSWORD}
    ports:
      - "${PG__PORT}:5432"
    volumes:
      - agic_pg:/var/lib/postgresql/data
    networks:
      - backend

  agic-pgadmin:
    image: dpage/pgadmin4:latest
    container_name: agic-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - agic-pg
    volumes:
      - agic_pgadmin:/var/lib/pgadmin
    networks:
      - backend

volumes:
  agic_pg:
    name: docker_compose_agic_pg
  agic_pgadmin:
    name: docker_compose_agic_pgadmin

networks:
  backend:
    driver: bridge
