name: project-name

services:
  project-name-redis:
    image: redis:7.2
    container_name: project-name-redis
    restart: unless-stopped
    ports:
      - "${REDIS__PORT}:6379"
    environment:
      - REDIS_PASSWORD=${REDIS__PASSWORD}
    command: >
      redis-server --appendonly yes --appendfsync everysec --maxmemory 512mb
      --maxmemory-policy allkeys-lru --requirepass ${REDIS__PASSWORD}
    volumes:
      - project_name_redis_data:/data
    networks:
      - backend

volumes:
  project_name_redis_data:
    name: docker_compose_project_name_redis_data

networks:
  backend:
    driver: bridge
